### ISSUE TITLE
Just a thought

### ISSUE THREAD

**Issue by dlevi309** [milahu/dogbolt-cli-client-bash#1]
First of all, thanks for this (it’s really sick!)

second, and hear me out, I think you should consider maybe taking it down :p if this gets any attention from the dogbolt team, they’ll probably add safeguards to prevent users from using this (I don’t think they want users to use any interface other than the site, but regardless, if enough people see this repo and start using it, the traffic on the site will skyrocket which would be enough reason alone for the team to push out an update with some preventative measures against 3rd party tools)

just a thought, either way again, thank you for this again. Can’t wait to start automating Hex-Rays decompilation 😝

**Comment by milahu** [comment]
nope sorry : P
you could as well ask dogbolt to take down their service

i already gave this some thought before your post...
dogbolt is already limited by file size (2 MB)
and they have some rate-limiting based on IP address

in a few months, hex-rays-8.3 will show up as a torrent...
on my linux box, the latest working version is IDA 6.8
(would be nice to have a CLI interface for that...)
on newer versions of IDA, wine fails with
"ShellExecuteEx failed: Bad EXE format"
(if this had higher priority, i would run it in a windows VM)
the latest torrent version i see is IDA 7.3 or 7.7
(would be interesting to compare the decompiler results between versions)

i really dont believe that dogbolt is hurting hex-rays
because IDA Pro is so expensive (about 5000 usd)
that they have only clients from the high-level software industry

**Comment by dlevi309** [comment]
fair enough, hoping for the best then 😄
